apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: mydataapp
type: Opaque
data:
  postgres-user: bXl1c2Vy
  postgres-password: bXlwYXNzd29yZA==
  postgres-db: bXlkYXRhYmFzZQ==
